export const pixelDictionary = [
	{
		name: "event info",
		items: [
			{ name: "actionSource", value: "Action Source" },
			{ name: "batchID", value: "BatchID" },
			{ name: "batchItemID", value: "Batch Item ID" },
			{ name: "eid", value: "Event ID" },
			{ name: "en", value: "Event Name" },
			{ name: "e", value: "Event Name" },
			{ name: "eventSource", value: "Event Source" },
			{ name: "et", value: "Event Time" },
			{ name: "trafficSource", value: "Traffic Source" },
			{ name: "reg_status", value: "Reg Status" },
			{ name: "ref", value: "Referrer" },
			{ name: "url", value: "URL" },
			{ name: "u", value: "URL" },
			{ name: "t", value: "Timestamp" },
			{ name: "v", value: "Version" },
			{ name: "i", value: "Client ID" },
			{ name: "n", value: "Sequence Number" },
			{ name: "d", value: "Domain" },
			{ name: "l", value: "Page Title" },
			{ name: "err", value: "Error" },
			{ name: "data", value: "Event Data" },
			{ name: "b", value: "Batch Number" },
			{ name: "c", value: "Cookies" },
			{ name: "o", value: "Origin" },
			{ name: "r", value: "Referrer" },
			{ name: "s", value: "Session" },
		],
	},
	{
		name: "tracking info",
		items: [
			{ name: "googleAdID", value: "Google Ad ID" },
			{ name: "googleAnalyticsClientID", value: "Google Analytics Client ID" },
			{ name: "googleClickID", value: "Google Click ID" },
			{ name: "instagramAccountID", value: "Instagram Account ID" },
			{ name: "instagramSID", value: "Instagram SID" },
			{ name: "klaviyoCampaignID", value: "Klaviyo Campaign ID" },
			{ name: "klaviyoClickID", value: "Klaviyo Click ID" },
			{ name: "klaviyoFlowID", value: "Klaviyo Flow ID" },
			{ name: "metaAdID", value: "Meta Ad ID" },
			{ name: "metaClickID", value: "Meta Click ID" },
			{ name: "fbc", value: "Meta FBC" },
			{ name: "fbp", value: "Meta FBP" },
			{ name: "metaLeadID", value: "Meta Lead ID" },
			{ name: "metaTransactionID", value: "Meta Transaction ID" },
			{ name: "metaTransactionStatus", value: "Meta Transaction Status" },
			{ name: "microsoftAdID", value: "Microsoft Ad ID" },
			{ name: "microsoftClickID", value: "Microsoft Click ID" },
			{ name: "pinterestAdID", value: "Pinterest Ad ID" },
			{ name: "snapchatAdID", value: "Snapchat Ad ID" },
			{ name: "snapchatClickID", value: "Snapchat Click ID" },
			{ name: "tikTokAdID", value: "TikTok Ad ID" },
			{ name: "tikTokClickID", value: "TikTok Click ID" },
			{ name: "utmCampaign", value: "Utm Campaign" },
			{ name: "utmContent", value: "Utm Content" },
			{ name: "utmID", value: "Utm ID" },
			{ name: "utmMedium", value: "Utm Medium" },
			{ name: "utmSource", value: "Utm Source" },
			{ name: "utmTerm", value: "Utm Term" },
			{ name: "whatsappID", value: "Whatsapp ID" },
			{ name: "xAdID", value: "XAd ID" },
		],
	},
	{
		name: "product info",
		items: [
			{ name: "content_category", value: "Content Category" },
			{ name: "content_ids", value: "Content IDs" },
			{ name: "content_name", value: "Content Name" },
			{ name: "content_type", value: "Content Type" },
			{ name: "contents", value: "Contents" },
			{ name: "currency", value: "Currency Original" },
			{ name: "num_items", value: "Num Items" },
			{ name: "order_id", value: "Order ID" },
			{ name: "orderMetadata", value: "Order Metadata" },
			{ name: "shopifyCartToken", value: "Shopify Cart Token" },
			{ name: "shopifyCheckoutToken", value: "Shopify Checkout Token" },
			{ name: "value", value: "Value" },
		],
	},
	{
		name: "device info",
		items: [
			{ name: "browser", value: "Browser" },
			{ name: "bid", value: "Browser ID" },
			{ name: "bl", value: "Browser Language" },
			{ name: "browserVersion", value: "Browser Version" },
			{ name: "device", value: "Device" },
			{ name: "deviceType", value: "Device Type" },
			{ name: "ip", value: "IP" },
			{ name: "screenOrientation", value: "Screen Orientation" },
			{ name: "screenResolution", value: "Screen Resolution" },
			{ name: "metaFBP", value: "Meta FBP" },
			{ name: "shopifySessionHash", value: "Shopify Session Hash" },
			{ name: "userAgent", value: "User Agent" },
			{ name: "a", value: "User Agent" },
			{ name: "so", value: "Screen Orientation" },
			{ name: "sr", value: "Screen Resolution" },
		],
	},
	{
		name: "personal info",
		items: [
			{ name: "a1", value: "Address 1" },
			{ name: "a2", value: "Address 2" },
			{ name: "city", value: "City" },
			{ name: "country", value: "Country" },
			{ name: "customerID", value: "Customer ID" },
			{ name: "db", value: "Date Of Birth" },
			{ name: "em", value: "Email" },
			{ name: "fn", value: "First Name" },
			{ name: "ge", value: "Gender" },
			{ name: "ln", value: "LastName" },
			{ name: "latitude", value: "Latitude" },
			{ name: "longitude", value: "Longitude" },
			{ name: "phone", value: "Phone" },
			{ name: "postalCode", value: "Postal Code" },
			{ name: "zp", value: "Zip Code" },
			{ name: "timeZone", value: "Time Zone" },
			{ name: "klaviyoProfileID", value: "Klaviyo Profile ID" },
			{ name: "shopifyCustomerID", value: "Shopify Customer ID" },
			{ name: "ph", value: "Phone" },
		],
	},
];

export const gaDictionary = [
	{
		name: "event info",
		items: [
			{ name: "en", value: "Event Name" },
			{
				name: "epn.percent_scrolled",
				value: "Event Parameter - Percent Scrolled",
			},
			{ name: "tid", value: "Tracking ID" },
			{ name: "gtm", value: "Google Tag Manager" },
			{ name: "_p", value: "GA4 Client ID" },
			{ name: "tag_exp", value: "Tag Expiration" },
			{ name: "tfd", value: "Time to First Byte (TTFB)" },
			{ name: "ep.content_id", value: "Event Parameter ID" },
			{ name: "ep.content_type", value: "Event Parameter Type" },
			{ name: "ep.screen_name", value: "Event Parameter Name" },
		],
	},
	{
		name: "tracking info",
		items: [
			{ name: "cid", value: "Client ID" },
			{ name: "gcd", value: "Google Client Data" },
			{ name: "npa", value: "Non-Personalized Ads" },
			{ name: "utmCampaign", value: "UTM Campaign" },
			{ name: "utmContent", value: "UTM Content" },
			{ name: "utmMedium", value: "UTM Medium" },
			{ name: "utmSource", value: "UTM Source" },
			{ name: "utmTerm", value: "UTM Term" },
			{ name: "dr", value: "Document Referrer" },
			{ name: "dl", value: "Document Location" },
			{ name: "dt", value: "Document Title" },
			{ name: "dma", value: "DMA (Designated Market Area)" },
			{ name: "pscdl", value: "PSCDL (Data Layer)" },
			{ name: "_s", value: "Session Counter" },
			{ name: "_ee", value: "Engagement Event" },
		],
	},
	{
		name: "product info",
		items: [
			{ name: "currency", value: "Currency" },
			{ name: "value", value: "Value" },
			{ name: "content_category", value: "Content Category" },
			{ name: "content_ids", value: "Content IDs" },
			{ name: "content_name", value: "Content Name" },
			{ name: "content_type", value: "Content Type" },
			{ name: "pr1", value: "Product ID (pr1)" },
			{ name: "epn.value", value: "Event Parameter Value" },
		],
	},
	{
		name: "device info",
		items: [
			{ name: "ul", value: "User Language" },
			{ name: "sr", value: "Screen Resolution" },
			{ name: "uaa", value: "User Agent Architecture" },
			{ name: "uab", value: "User Agent Browser" },
			{ name: "uafvl", value: "User Agent Full Version List" },
			{ name: "uamb", value: "User Agent Mobile" },
			{ name: "uam", value: "User Agent Model" },
			{ name: "uap", value: "User Agent Platform" },
			{ name: "uapv", value: "User Agent Platform Version" },
			{ name: "uaw", value: "User Agent Width" },
			{ name: "are", value: "Adblock Enabled" },
			{ name: "frm", value: "Frame Depth" },
		],
	},
	{
		name: "personal info",
		items: [
			{ name: "sid", value: "Session ID" },
			{ name: "sct", value: "Session Count" },
			{ name: "seg", value: "Session Engagement" },
			{ name: "ph", value: "Phone" },
		],
	},
];

export const metaDictionary = [
	{
		name: "event info",
		items: [
			{ name: "id", value: "Pixel ID" },
			{ name: "ev", value: "Event Name" },
			{ name: "ts", value: "Timestamp" },
			{ name: "cd[pxid]", value: "Pixel ID (cd)" },
			{ name: "cd[eid]", value: "Event ID" },
			{ name: "cd[en]", value: "Event Name" },
			{ name: "cd[eventID]", value: "Event ID (cd)" },
			{ name: "cd[et]", value: "Event Time" },
		],
	},
	{
		name: "tracking info",
		items: [
			{ name: "fbp", value: "Facebook FBP" },
			{ name: "cd[fbp]", value: "Facebook FBP (cd)" },
			{ name: "v", value: "Facebook Pixel Version" },
			{ name: "r", value: "Facebook Pixel Status" },
			{ name: "rqm", value: "Request Method" },
			{ name: "cdl", value: "Client Data Layer" },
			{ name: "ler", value: "Last Event Result" },
			{ name: "coo", value: "Cookies Opt-out" },
			{ name: "ec", value: "Event Count" },
			{ name: "o", value: "Offset" },
			{ name: "it", value: "Initialization Time" },
			{ name: "if", value: "Iframe" },
		],
	},
	{
		name: "product info",
		items: [
			{ name: "dl", value: "Document Location (Product URL)" },
			{ name: "cd[url]", value: "Content URL" },
			{ name: "cd[ref]", value: "Referrer URL" },
			{ name: "rl", value: "Referrer Location" },
			{ name: "cd[content_ids]", value: "Content IDs" },
			{ name: "cd[content_name]", value: "Content Name" },
			{ name: "cd[content_type]", value: "Content Type" },
			{ name: "cd[contents]", value: "Contents" },
			{ name: "cd[num_items]", value: "Number of Items" },
			{ name: "cd[currency]", value: "Currency" },
			{ name: "cd[value]", value: "Value" },
		],
	},
	{
		name: "device info",
		items: [
			{ name: "cd[bid]", value: "Browser ID" },
			{ name: "cd[bl]", value: "Browser Language" },
			{ name: "cd[so]", value: "Screen Orientation" },
			{ name: "cd[sr]", value: "Screen Resolution" },
			{ name: "sw", value: "Screen Width" },
			{ name: "sh", value: "Screen Height" },
		],
	},
	{
		name: "personal info",
		items: [
			{ name: "cd[em]", value: "Email" },
			{ name: "cd[ph]", value: "Phone" },
			{ name: "cd[country]", value: "Country" },
			{ name: "cd[shct]", value: "Shortened Hashed Contact" },
			{ name: "cd[sco]", value: "State Code" },
			{ name: "ph", value: "Phone" },
		],
	},
];

export const tiktokDictionary = [
	{
		name: "event info",
		items: [
			{ name: "event", value: "Event Name" },
			{ name: "context_pixel_code", value: "Pixel Code" },
			{ name: "timestamp", value: "Timestamp" },
		],
	},
	{
		name: "tracking info",
		items: [
			{ name: "user_agent", value: "User Agent" },
			{ name: "ip", value: "IP Address" },
			{ name: "url", value: "URL" },
		],
	},
];

export const gtmDictionary = [
	{
		name: "event info",
		items: [
			{ name: "gtm", value: "Google Tag Manager ID" },
			{ name: "event", value: "Event Name" },
			{ name: "event_name", value: "Event Name" },
			{ name: "event_category", value: "Event Category" },
			{ name: "event_action", value: "Event Action" },
			{ name: "event_label", value: "Event Label" },
			{ name: "event_value", value: "Event Value" },
		],
	},
	{
		name: "tracking info",
		items: [
			{ name: "tid", value: "Tracking ID" },
			{ name: "cid", value: "Client ID" },
			{ name: "dl", value: "Document Location" },
			{ name: "dt", value: "Document Title" },
			{ name: "dr", value: "Document Referrer" },
			{ name: "ul", value: "User Language" },
			{ name: "sr", value: "Screen Resolution" },
			{ name: "u_w", value: "User Width" },
			{ name: "u_h", value: "User Height" },
			{ name: "uap", value: "User Agent Platform" },
			{ name: "uapv", value: "User Agent Platform Version" },
			{ name: "uaa", value: "User Agent Architecture" },
			{ name: "uab", value: "User Agent Browser" },
			{ name: "uafvl", value: "User Agent Full Version List" },
			{ name: "uamb", value: "User Agent Mobile" },
			{ name: "uam", value: "User Agent Model" },
			{ name: "uaw", value: "User Agent Width" },
		],
	},
	{
		name: "page info",
		items: [
			{ name: "URL", value: "Page URL" },
			{ name: "tiba", value: "Page Title" },
			{ name: "bg", value: "Background Color" },
			{ name: "fmt", value: "Format" },
			{ name: "cv", value: "Client Version" },
			{ name: "fst", value: "First Hit Time" },
			{ name: "random", value: "Random" },
			{ name: "guid", value: "GUID" },
			{ name: "auid", value: "Analytics User ID" },
		],
	},
	{
		name: "device info",
		items: [
			{ name: "dma", value: "DMA (Designated Market Area)" },
			{ name: "dma_cps", value: "DMA CPS" },
			{ name: "npa", value: "Non-Personalized Ads" },
			{ name: "gcs", value: "Google Client Data" },
			{ name: "gcd", value: "Google Client Data" },
			{ name: "pscdl", value: "PSCDL (Data Layer)" },
			{ name: "_is_sw", value: "Is Service Worker" },
			{ name: "tag_exp", value: "Tag Expiration" },
			{ name: "_tu", value: "Tracking User" },
		],
	},
];
